### ISSUE TITLE
No es mostra correctament el top 3 en casos d'empat

### ISSUE THREAD

**Issue by SnappySM** [Learning-Dashboard/GLiDe-Frontend#3]
Quan hi ha un empat a qualsevol de les tres primeres posicions del leaderboard només es mostra el jugador amb el primer nom en ordre alfabètic. Primer cal determinar com es volen gestionar els casos d'empat i després modificar la visualització perquè s'hi ajusti.

**Comment by SnappySM** [comment]
Fer servir el moment en el qual s'ha aconseguit l'achievement per desempatar (al gamification engine)

**Comment by SnappySM** [comment]
Es pot fer que només es mostri el podi quan hi ha un top 3 sense empats

**Comment by carlesf** [comment]
Regla: si no hi ha 3 amb puntuació diferent al capdavant, no hi ha pòdium
